#!/bin/bash
# validAlphaNum--Ensures that input consists only of alphabetical
#   and numeric characters.

validAlphaNum()
{
  # Validate arg: returns 0 if all upper+lower+digits, 1 otherwise.
  # Remove all unacceptable chars.

  # 耗子叔的 sed 教程：https://coolshell.cn/articles/9104.html/
  # 非字母数字字符
  # validchars="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"

  #[] 表示字符集，前面加一个 ^，表示取反的意思。
  # s 表示替换命令，/[^[:upper:] ,.]/表示匹配非大写、非,. ，//表示空，实际上就是去掉，/g 表示一行上的替换所有的匹配
  validchars="$(echo $1 | sed 's/[^[:upper:] ,.]//g')"

  if [ "$validchars" = "$1" ] ; then
    return 0
  else
    return 1
  fi
}

# BEGIN MAIN SCRIPT-–DELETE EVERYTHING BELOW THIS LINE IF YOU
#   WANT TO INCLUDE THIS IN OTHER SCRIPTS.
# =================
/bin/echo -n "Enter input: "
read input

# Input validation
if ! validAlphaNum "$input" ; then
 echo "Your input must consist of only letters and numbers." >&2
 exit 1
else
 echo "Input is valid."
fi

exit 0
